### ISSUE TITLE
Q: How to iterate through all torrents / Cannot delete torrents

### ISSUE THREAD

**Issue by DestinyofYeet** [Koro33/qbit-api-rs#3]
Hello, this may sound a bit stupid, but how do I iterate through all the torrents?

**Comment by koro33e** [comment]
This?

https://github.com/Koro33/qbit-api-rs/blob/caea460be40968ca1277afa9fb1e7fdb54199041/src/client.rs#L250-L253

Initialize a client & call this method

**Comment by DestinyofYeet** [comment]
Well yes, but what do I put in as the `q` argument?

**Comment by koro33e** [comment]
see types

https://github.com/Koro33/qbit-api-rs/blob/caea460be40968ca1277afa9fb1e7fdb54199041/src/types.rs#L570

For the meaning of each field, you should refer to the docs of qbittorrent webapi (links in README).

**Comment by DestinyofYeet** [comment]
Ah thanks

And maybe this should be a seperate issue, but I also can't seem to find how to delete a torrent. I can delete categories, trackers and tags, but not a torrent itself.

**Comment by koro33e** [comment]
Some methods are missed. I'll fix it later.

**Comment by DestinyofYeet** [comment]
Ah okay, thanks :D
